version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - DB_URI
      - JWT_SECRET
      - NODE_ENV=production
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
  proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - 5555:80
